//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pe.ByS.ERP.Aplicacion.Core.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MensajesSistema {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MensajesSistema() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pe.ByS.ERP.Aplicacion.Core.Message.MensajesSistema", typeof(MensajesSistema).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede copiar los estadios de un mismo registro.
        /// </summary>
        public static string CopiarEstadioIgual {
            get {
                return ResourceManager.GetString("CopiarEstadioIgual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El registro no existe.
        /// </summary>
        public static string CopiarEstadioNoExiste {
            get {
                return ResourceManager.GetString("CopiarEstadioNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elija otro registro, este no contiene estadios.
        /// </summary>
        public static string CopiarEstadioNoTiene {
            get {
                return ResourceManager.GetString("CopiarEstadioNoTiene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurrió un error inesperado. Inténtelo nuevamente..
        /// </summary>
        public static string EtiquetaError {
            get {
                return ResourceManager.GetString("EtiquetaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un estadio con la misma Descripción..
        /// </summary>
        public static string FlujoAprobacionEstadioDescripcionExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionEstadioDescripcionExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un estadio con los mismos datos de Orden de Prioridad y Descripción.
        /// </summary>
        public static string FlujoAprobacionEstadioExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionEstadioExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un estadio con el mismo orden de prioridad.
        /// </summary>
        public static string FlujoAprobacionEstadioOrdenExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionEstadioOrdenExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un flujo de aprobación con los mismos datos..
        /// </summary>
        public static string FlujoAprobacionExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se ha configurado un Flujo de Aprobación para la Forma de Edición {0}..
        /// </summary>
        public static string FlujoAprobacionFormaEdicionNoExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionFormaEdicionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe un Flujo de Aprobación con la Unidad Operativa, Tipo de Servicio, Tipo de Requerimiento ingresado..
        /// </summary>
        public static string FlujoAprobacionNoExiste {
            get {
                return ResourceManager.GetString("FlujoAprobacionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe un Flujo de Aprobación con la Unidad Operativa, Tipo de Servicio, Tipo de Requerimiento y Forma de Edición ingresado..
        /// </summary>
        public static string FlujoAprobacionNoExisteReporte {
            get {
                return ResourceManager.GetString("FlujoAprobacionNoExisteReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debe establecer un Orden mayor a 1..
        /// </summary>
        public static string FlujoAprobacionOrdenIgualUno {
            get {
                return ResourceManager.GetString("FlujoAprobacionOrdenIgualUno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede registrar una combinación ya existente..
        /// </summary>
        public static string PlantillaExiste {
            get {
                return ResourceManager.GetString("PlantillaExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No puede registrar una Fecha de Inicio de Vigencia menor a la que ya existe..
        /// </summary>
        public static string PlantillaFechaInicioVigenciaMenor {
            get {
                return ResourceManager.GetString("PlantillaFechaInicioVigenciaMenor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El formato de la Fecha de Inicio de Vigencia es incorrecto..
        /// </summary>
        public static string PlantillaFechaInicioVigenciIncorrecto {
            get {
                return ResourceManager.GetString("PlantillaFechaInicioVigenciIncorrecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe una Plantilla ni un Flujo de Aprobación para la combinación ingresada..
        /// </summary>
        public static string PlantillaFlujoAprobacionNoExiste {
            get {
                return ResourceManager.GetString("PlantillaFlujoAprobacionNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe una Plantilla con el Tipo de Servicio, Tipo de Requerimiento y Tipo de Documento ingresado..
        /// </summary>
        public static string PlantillaNoExiste {
            get {
                return ResourceManager.GetString("PlantillaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ya existe un Párrafo con el mismo Orden y Título para la Plantilla..
        /// </summary>
        public static string PlantillaParrafoExiste {
            get {
                return ResourceManager.GetString("PlantillaParrafoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No existe un Párrafo para la Plantilla seleccionada..
        /// </summary>
        public static string PlantillaParrafoNoExiste {
            get {
                return ResourceManager.GetString("PlantillaParrafoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Orden del Párrafo ya se encuentra registrada para esta Plantilla..
        /// </summary>
        public static string PlantillaParrafoOrdenExiste {
            get {
                return ResourceManager.GetString("PlantillaParrafoOrdenExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Título del Párrafo ya se encuentra registrada para esta Plantilla..
        /// </summary>
        public static string PlantillaParrafoTituloExiste {
            get {
                return ResourceManager.GetString("PlantillaParrafoTituloExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unidad Operativa Y  Fecha planificada, no pueden tener datos iguales..
        /// </summary>
        public static string ProcesoAuditoriaExiste {
            get {
                return ResourceManager.GetString("ProcesoAuditoriaExiste", resourceCulture);
            }
        }
    }
}
